### ISSUE TITLE
CTRL+C doesn't do anything

### ISSUE THREAD

**Issue by oren** [mafintosh/hyperfs#1]
I am on ubuntu 15.04. CTRL+C (in both open terminals) doesn't do anything:

In terminal 1
```
npm install -g hyperfs
hyperfs create test
hyperfs mount test ./mnt
```

In terminal 2
```
mkdir mnt/test
echo hello world > mnt/test/hello.txt
```

`CTRL+C` in both terminals doesn't do anything.

**Comment by mafintosh** [comment]
it does unmount the file system in the first terminal?

**Comment by oren** [comment]
restarted my machine and now it's ok. i'll let you know if i can reproduce it again. thanks!
