### ISSUE TITLE
ls command shows an error and I can't rm the mnt folder

### ISSUE THREAD

**Issue by oren** [mafintosh/hyperfs#2]
ls 

```
ls: cannot access mnt: Transport endpoint is not connected
```

sudo rm -r mnt
```
rm: cannot remove ‘mnt’: Is a directory
```

**Comment by mafintosh** [comment]
could you see if there is something mounted on the mnt mountpoint? i think just running `mount` will show you that

**Comment by oren** [comment]
I was able to `rm` it after restart. it was probably still mounted. thanks!
